project: desid
ignore_patterns: ["models/**/*/_*.*", "models/**/**/*/_*.*", "models/**/**/**/*/_*.*"]
gateways:
    local:
        connection:
            type: duckdb
            database: data/catalog.db
            connector_config:
                threads: 16
                memory_limit: 45G
            extensions: [spatial, sqlite]
        state_connection:
            type: duckdb
            database: data/state.db

default_gateway: local

model_defaults:
    dialect: duckdb, normalization_strategy=case_sensitive

