MODEL (
    name siops.historico_contas,
    kind FULL
);
SELECT
    ITEM.CO_ITEM_EXIBICAO AS CONTA,
    ITEM.NO_ITEM AS NOME_CONTA,
    CASE WHEN C.CO_ITEM IS NOT NULL THEN 'OPERACIONAL' ELSE 'AGREGADORA' END AS TIPO_CONTA,
    CASE WHEN SUM(CASE WHEN PERFED.CO_ENTE_FEDERADO = 2 THEN 1 ELSE 0 END) > 0 THEN 'S' ELSE 'N' END AS ATIVO_ESTADO,
    CASE WHEN SUM(CASE WHEN PERFED.CO_ENTE_FEDERADO = 3 THEN 1 ELSE 0 END) > 0 THEN 'S' ELSE 'N' END AS ATIVO_DF,
    CASE WHEN SUM(CASE WHEN PERFED.CO_ENTE_FEDERADO = 1 THEN 1 ELSE 0 END) > 0 THEN 'S' ELSE 'N' END AS ATIVO_MUNICIPIO,
    'N' AS ATIVO_UNIAO,
    p.PERIODO,
    MAX(DT.DATA_ATUALIZACAO) AS DATA_ATUALIZACAO
FROM
    RAW_SIOPSUF.RL_PROJ_ANOPERIODO_ENTE_FED AS PERFED
    JOIN RAW_SIOPSUF.RL_PROJ_ANOPERIODOENTE_PASTA AS PERFEDPASTA
        ON PERFED.CO_SEQ_ANO_PER_ENTE_FED = PERFEDPASTA.CO_ANOPERIODO_ENTE_FED
    JOIN RAW_SIOPSUF.TB_PROJ_PASTA AS PASTA
        ON PERFEDPASTA.CO_PASTA = PASTA.CO_SEQ_PASTA
    JOIN RAW_SIOPSUF.RL_PROJ_PASTA_ITEM AS PASTAITEM
        ON PERFEDPASTA.CO_SEQ_ANO_PER_ENTE_PASTA = PASTAITEM.CO_ANO_PER_ENTE_PASTA
    JOIN RAW_SIOPSUF.TB_PROJ_ITEM AS ITEM
        ON PASTAITEM.CO_ITEM = ITEM.CO_SEQ_ITEM
    LEFT JOIN tmp_contas_operacionais AS C
        ON ITEM.CO_SEQ_ITEM = C.CO_ITEM
    LEFT JOIN (
        SELECT
            CO_ANO_PER_ENTE_FED,
            MIN(DT_DISPONIBILIZACAO) AS DATA_ATUALIZACAO
        FROM
            RAW_SIOPSUF.TB_PROJ_ESTRUTURA_VERSAO
        WHERE
            DS_VERSAO = '1.0'
        GROUP BY
            CO_ANO_PER_ENTE_FED
    ) AS DT
        ON DT.CO_ANO_PER_ENTE_FED = PERFED.CO_SEQ_ANO_PER_ENTE_FED
    JOIN siops__dev.periodos p
        ON CAST(DT.DATA_ATUALIZACAO AS DATE) BETWEEN p.DATA_INICIO AND p.DATA_FIM
WHERE
    PERFED.CO_ENTE_FEDERADO IN (1, 2, 3)
    AND PASTA.CO_SEQ_PASTA IN (1, 2)
GROUP BY
    CONTA,
    NOME_CONTA,
    TIPO_CONTA,
    p.PERIODO
ORDER BY 
    DATA_ATUALIZACAO;