MODEL (
    name raw.sisab__tipos,
    kind FULL
);
    
select #1 as tabela, #2 as chave, #3 as valor FROM (
    VALUES
    -- LOCAL DE ATENDIMENTO
    ('LOCAL_DE_ATENDIMENTO', 1, 'UBS'),
    ('LOCAL_DE_ATENDIMENTO', 2, 'Unidade móvel'),
    ('LOCAL_DE_ATENDIMENTO', 3, 'Rua'),
    ('LOCAL_DE_ATENDIMENTO', 4, 'Domicílio'),
    ('LOCAL_DE_ATENDIMENTO', 5, 'Escola / Creche'),
    ('LOCAL_DE_ATENDIMENTO', 6, 'Outros'),
    ('LOCAL_DE_ATENDIMENTO', 7, 'Polo (academia da saúde)'),
    ('LOCAL_DE_ATENDIMENTO', 8, 'Instituição / Abrigo'),
    ('LOCAL_DE_ATENDIMENTO', 9, 'Unidade prisional ou congêneres'),
    ('LOCAL_DE_ATENDIMENTO', 10, 'Unidade socioeducativa'),
    ('LOCAL_DE_ATENDIMENTO', 11, 'Hospital'),
    ('LOCAL_DE_ATENDIMENTO', 12, 'Unidade de pronto atendimento'),
    ('LOCAL_DE_ATENDIMENTO', 13, 'CACON / UNACON'),
    ('LOCAL_DE_ATENDIMENTO', 14, 'Hospital SOS Urgência / Emergência'),
    ('LOCAL_DE_ATENDIMENTO', 15, 'Hospital SOS demais setores'),

    -- PRATICAS INTEGRATIVAS COMPLEMENTARES
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 1, 'Medicina tradicional chinesa'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 2, 'Antroposofia aplicado a saúde'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 3, 'Homeopatia'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 4, 'Fitoterapia'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 5, 'Termalismo / Crenoterapia'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 6, 'Práticas corporais e mentais em PICS'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 7, 'Técnicas manuais em PICS'),
    ('PRATICAS_INTEGRATIVAS_COMPLEMENTARES', 8, 'Outros'),

    -- PRATICAS TEMAS PARA SAUDE
    ('PRATICAS_TEMAS_PARA_SAUDE', 1, 'Alimentação saudável'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 2, 'Aplicação tópica de fluor'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 3, 'Saúde ocular'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 4, 'Autocuidado de pessoas com doenças crônicas'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 5, 'Cidadania e direitos homanos'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 6, 'Saúde do trabalhador'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 7, 'Dependência química / tabaco / álcool / outras drogas'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 8, 'Envelhecimento / Climatério / Andropausa / Etc'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 9, 'Escovação dentária supervisionada'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 10, 'Plantas medicinais / Fitoterapia'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 11, 'Práticas corporais / Atividade física'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 12, 'Práticas corporais e mentais em PIC'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 13, 'Prevenção da violência e promoção da cultura da paz'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 14, 'Saúde ambiental'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 15, 'Saúde bucal'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 16, 'Saúde mental'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 17, 'Saúde sexual e reprodutiva'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 18, 'Semana saúde na escola'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 19, 'Agravos negligenciados'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 20, 'Antropometria'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 21, 'Outros'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 22, 'Saúde auditiva'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 23, 'Desenvolvimento da linguagem'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 24, 'Verificação da situação vacinal'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 25, 'PNCT 1'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 26, 'PNCT 2'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 27, 'PNCT 3'),
    ('PRATICAS_TEMAS_PARA_SAUDE', 28, 'PNCT 4'),

    -- TIPO ATIVIDADE COLETIVA
    ('TIPO_ATIVIDADE_COLETIVA', 1, 'Reunião de equipe'),
    ('TIPO_ATIVIDADE_COLETIVA', 2, 'Reunião com outras equipes de saúde'),
    ('TIPO_ATIVIDADE_COLETIVA', 3, 'Reunião intersetorial / Conselho local de saúde / Controle social'),
    ('TIPO_ATIVIDADE_COLETIVA', 4, 'Educação em saúde'),
    ('TIPO_ATIVIDADE_COLETIVA', 5, 'Atendimento em grupo'),
    ('TIPO_ATIVIDADE_COLETIVA', 6, 'Avaliação / Procedimento coletivo'),
    ('TIPO_ATIVIDADE_COLETIVA', 7, 'Mobilização social'),

    -- TIPO_FICHA_ATENDIMENTO
    ('TIPO_FICHA_ATENDIMENTO', 2, 'Ficha de Cadastro Individual'),
    ('TIPO_FICHA_ATENDIMENTO', 3, 'Ficha de Cadastro Domiciliar'),
    ('TIPO_FICHA_ATENDIMENTO', 4, 'Ficha de Atendimento Individual'),
    ('TIPO_FICHA_ATENDIMENTO', 5, 'Ficha de Atendimento Odontológico'),
    ('TIPO_FICHA_ATENDIMENTO', 6, 'Ficha de Atividade Coletiva'),
    ('TIPO_FICHA_ATENDIMENTO', 7, 'Ficha de Procedimentos'),
    ('TIPO_FICHA_ATENDIMENTO', 8, 'Ficha de Visita Domiciliar'),
    ('TIPO_FICHA_ATENDIMENTO', 10, 'Ficha de Atendimento Domiciliar'),
    ('TIPO_FICHA_ATENDIMENTO', 11, 'Ficha de Avaliação de Elegibilidade'),
    ('TIPO_FICHA_ATENDIMENTO', 12, 'Marcadores de Consumo Alimentar'),

    -- TIPO_ATENDIMENTO
    ('TIPO_ATENDIMENTO', 1, 'Consulta agendada programada / Cuidado continuado'),
    ('TIPO_ATENDIMENTO', 2, 'Consulta agendada'),
    ('TIPO_ATENDIMENTO', 4, 'Escuta inicial / Orientação'),
    ('TIPO_ATENDIMENTO', 5, 'Consulta no dia'),
    ('TIPO_ATENDIMENTO', 6, 'Atendimento de urgência'),
    ('TIPO_ATENDIMENTO', 7, 'Atendimento programado'),
    ('TIPO_ATENDIMENTO', 8, 'Atendimento não programado'),

    -- TIPO_DE_CONSULTA_ODONTO
    ('TIPO_DE_CONSULTA_ODONTO', 1, 'Primeira consulta odontológica programática'),
    ('TIPO_DE_CONSULTA_ODONTO', 2, 'Consulta de retorno'),
    ('TIPO_DE_CONSULTA_ODONTO', 4, 'Consulta de manutenção'),

    -- VIGILANCIA_EM_SAUDE_BUCAL
    ('VIGILANCIA_EM_SAUDE_BUCAL', 1, 'Abscesso dento alveolar'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 2, 'Alteração em tecidos moles'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 3, 'Dor de dente'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 4, 'Fendas / Fissuras lábio palatais'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 5, 'Fluorose dentária moderada / severa'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 6, 'Traumatismo dento alveolar'),
    ('VIGILANCIA_EM_SAUDE_BUCAL', 99, 'Não identificado'),

    -- TEMAS_PARA_REUNIAO
    ('TEMAS_PARA_REUNIAO', 1, 'Questões administrativas / funcionamento'),
    ('TEMAS_PARA_REUNIAO', 2, 'Processo de trabalho'),
    ('TEMAS_PARA_REUNIAO', 3, 'Diagnóstico / Monitoramento do território'),
    ('TEMAS_PARA_REUNIAO', 4, 'Planejamento / Monitoramento das ações da equipe'),
    ('TEMAS_PARA_REUNIAO', 5, 'Discussão de caso ou projeto terapêutico singular'),
    ('TEMAS_PARA_REUNIAO', 6, 'Educação permanente'),
    ('TEMAS_PARA_REUNIAO', 7, 'Outros'),

    -- MOTIVO_VISITA
    ('MOTIVO_VISITA', 1, 'Cadastramento / Atualização'),
    ('MOTIVO_VISITA', 29, 'Visita periódica'),
    ('MOTIVO_VISITA', 2, 'Consulta'),
    ('MOTIVO_VISITA', 3, 'Exame'),
    ('MOTIVO_VISITA', 4, 'Vacina'),
    ('MOTIVO_VISITA', 30, 'Condicionalidades do bolsa família'),
    ('MOTIVO_VISITA', 5, 'Gestante'),
    ('MOTIVO_VISITA', 6, 'Puérpera'),
    ('MOTIVO_VISITA', 7, 'Recém-nascido'),
    ('MOTIVO_VISITA', 8, 'Criança'),
    ('MOTIVO_VISITA', 9, 'Pessoa com desnutrição'),
    ('MOTIVO_VISITA', 10, 'Pessoa em reabilitação ou com deficiência'),
    ('MOTIVO_VISITA', 11, 'Pessoa com hipertensão'),
    ('MOTIVO_VISITA', 12, 'Pessoa com diabetes'),
    ('MOTIVO_VISITA', 13, 'Pessoa com asma'),
    ('MOTIVO_VISITA', 14, 'Pessoa com DPOC / enfisema'),
    ('MOTIVO_VISITA', 15, 'Pessoa com câncer'),
    ('MOTIVO_VISITA', 16, 'Pessoa com outras doenças crônicas'),
    ('MOTIVO_VISITA', 17, 'Pessoa com hanseníase'),
    ('MOTIVO_VISITA', 18, 'Pessoa com tuberculose'),
    ('MOTIVO_VISITA', 32, 'Sintomáticos respiratórios'),
    ('MOTIVO_VISITA', 33, 'Tabagista'),
    ('MOTIVO_VISITA', 19, 'Domiciliados / Acamados'),
    ('MOTIVO_VISITA', 20, 'Condições de vulnerabilidade social'),
    ('MOTIVO_VISITA', 21, 'Condicionalidades do bolsa família'),
    ('MOTIVO_VISITA', 22, 'Saúde mental'),
    ('MOTIVO_VISITA', 23, 'Usuário de álcool'),
    ('MOTIVO_VISITA', 24, 'Usuário de outras drogas'),
    ('MOTIVO_VISITA', 25, 'Egresso de internação'),
    ('MOTIVO_VISITA', 26, 'Controle de ambientes / vetores'),
    ('MOTIVO_VISITA', 27, 'Convite para atividades coletivas / campanha de saúde'),
    ('MOTIVO_VISITA', 31, 'Orientação / Prevenção'),
    ('MOTIVO_VISITA', 28, 'Outros'));